#!/usr/bin/env bash
# Generates and persists production secrets outside the git repo, in a
# root-only file scoped to elrenad.tech ($SECRETS_FILE, distinct from
# el-renad.com's own /etc/elrenad/secrets.env). Values are generated ONCE
# and reused on every future `sudo ./deploy/deploy.sh` run.

ensure_secrets() {
  mkdir -p "$SECRETS_DIR"
  chmod 700 "$SECRETS_DIR"
  touch "$SECRETS_FILE"
  chmod 600 "$SECRETS_FILE"

  # shellcheck disable=SC1090
  source "$SECRETS_FILE"

  local changed=0

  if [ -z "${JWT_SECRET:-}" ]; then
    JWT_SECRET="$(openssl rand -hex 32)"
    changed=1
    log_info "Generated a new JWT_SECRET."
  fi

  if [ -z "${MONGO_APP_PASSWORD:-}" ]; then
    MONGO_APP_PASSWORD="$(openssl rand -hex 24)"
    changed=1
    log_info "Generated a new MongoDB application-user password."
  fi

  if [ -z "${ADMIN_BOOTSTRAP_PASSWORD:-}" ]; then
    # Initial admin password for this deployment. This is the one place it
    # is allowed to exist in plaintext: a root-only (chmod 600) file outside
    # the git repository, used a single time to create a bcrypt hash. Never
    # logged, never reused once the account exists. Override before the
    # first deploy by exporting ADMIN_BOOTSTRAP_PASSWORD_OVERRIDE.
    ADMIN_BOOTSTRAP_PASSWORD="${ADMIN_BOOTSTRAP_PASSWORD_OVERRIDE:-$(openssl rand -base64 18)}"
    changed=1
    log_warn "Generated a new admin bootstrap password — see $SECRETS_FILE (root-only) to retrieve it."
  fi

  if [ "$changed" = "1" ]; then
    cat > "$SECRETS_FILE" <<EOF
# Auto-generated by deploy/deploy.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).
# Root-only. Never commit this file. Deleting a value here causes the next
# deploy run to regenerate it (which, for JWT_SECRET, invalidates every
# previously issued login token).
JWT_SECRET=$JWT_SECRET
MONGO_APP_PASSWORD=$MONGO_APP_PASSWORD
ADMIN_BOOTSTRAP_PASSWORD=$ADMIN_BOOTSTRAP_PASSWORD
EOF
    chmod 600 "$SECRETS_FILE"
  fi

  export JWT_SECRET MONGO_APP_PASSWORD ADMIN_BOOTSTRAP_PASSWORD
  log_ok "Secrets ready at $SECRETS_FILE (mode 600, root-only)."
}
